apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo
spec:
  initContainers:
  - name: sec-ctx-demo
    image: busybox
    command: [ "sh", "-c", "sleep 1h" ]
    securityContext:
      seLinuxOptions:
        level: "s0:c123,c456"
    volumeMounts:
    - name: sec-ctx-vol
      mountPath: /data/demo
    
